### PR TITLE
fix: remove hardcoded year from og tags

### PR DESCRIPTION
**Pull request by faran4engg**
## Description

Removed hardcoded year from og tags

## Related Issues

Fixes https://github.com/hacktoberfest-finder/hacktoberfest-finder/issues/223

## Checklist

* [x] I've added my name into `CONTRIBUTING.md`
* [x] I have read over the [Contributors Guide]() for this project

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Looks like your PR includes a bunch of auto-formatting of the Tailwind classes but I'll let it slip 😜 

Thanks - also realised the social image is out of date. I'll open another issue for that.

**Comment by faran4engg** [comment]
> Looks like your PR includes a bunch of auto-formatting of the Tailwind classes but I'll let it slip 😜
> 
> Thanks - also realised the social image is out of date. I'll open another issue for that.

You're welcome. Can you please assign this issue to me! I would love to fix that too 🙂

**Comment by duncanmcclean** [comment]
@faran4engg It's #225 - you can decide with the other person that's interested who should do the PR 😆

**Comment by NaveenKharwar** [comment]
It's is fine. @faran4engg, go ahead. I'll take some other repo. Thanks.

**Comment by faran4engg** [comment]
> It's fine. @faran4engg, go ahead. I'll take some other repo. Thanks.

Thanks @NaveenKharwar . 
@duncanmcclean I will create a generic image, so that we dont have to change every year 😃

**Pull request merged**
