### PR TITLE
fix: issue finder image updated

### PR DESCRIPTION
**Pull request by faran4engg**
## Description

updated issue finder image !

## Related Issues

Fixes https://github.com/hacktoberfest-finder/hacktoberfest-finder/issues/225

## Checklist

* [x] I've added my name into `CONTRIBUTING.md`
* [x] I have read over the [Contributors Guide]() for this project

### CODE REVIEW

**Comment by duncanmcclean** [comment]
GitHub won't let me preview the image because it's a binary file.. can you share the image here instead (just copy it in here)?

**Comment by faran4engg** [comment]
> GitHub won't let me preview the image because it's a binary file.. can you share the image here instead (just copy it in here)?

https://github.com/hacktoberfest-finder/hacktoberfest-finder/issues/225#issuecomment-932821334

issuefinder

**Comment by duncanmcclean** [comment]
Thanks!

Would you be able to remove the 'Signup now' and change the font of the main 'Hacktoberfest' text, for some reason it doesn't look right to me 🤔

Apart from that I think it looks great - hopefully they're not too big changes to make.

Thanks again!

PS: I'll be back on Monday, not going to be online tomorrow (Sunday).

**Comment by faran4engg** [comment]
> Thanks!
> 
> Would you be able to remove the 'Signup now' and change the font of the main 'Hacktoberfest' text, for some reason it doesn't look right to me 🤔
> 
> Apart from that I think it looks great - hopefully they're not too big changes to make.
> 
> Thanks again!
> 
> PS: I'll be back on Monday, not going to be online tomorrow (Sunday).

I'll update now... In 10-15 minutes :)

**Comment by faran4engg** [comment]
> > Thanks!
> > Would you be able to remove the 'Signup now' and change the font of the main 'Hacktoberfest' text, for some reason it doesn't look right to me 🤔
> > Apart from that I think it looks great - hopefully they're not too big changes to make.
> > Thanks again!
> > PS: I'll be back on Monday, not going to be online tomorrow (Sunday).
> 
> I'll update now... In 10-15 minutes :)

Update: How about now ? @duncanmcclean 

issuefinder

**Comment by faran4engg** [comment]
> > > Thanks!
> > > Would you be able to remove the 'Signup now' and change the font of the main 'Hacktoberfest' text, for some reason it doesn't look right to me 🤔
> > > Apart from that I think it looks great - hopefully they're not too big changes to make.
> > > Thanks again!
> > > PS: I'll be back on Monday, not going to be online tomorrow (Sunday).
> > 
> > 
> > I'll update now... In 10-15 minutes :)
> 
> Update: How about now ? @duncanmcclean
> 
> issuefinder

> @duncanmcclean , welcome back ! could you please update if this image is OK :) !

**Comment by duncanmcclean** [comment]
Sorry - meant to respond earlier.

Just checked the Netlify preview and it looks like the image is the wrong size. 

Your image: https://deploy-preview-226--hacktoberfest-finder.netlify.app/img/issuefinder.png
The current image: https://hacktoberfest-finder.netlify.app/img/issuefinder.png

The current one is a rectangular image whereas your one is a square. I'd prefer if we kept to the same size, if possible. (1200 x 630)

**Comment by faran4engg** [comment]
> Sorry - meant to respond earlier.
> 
> Just checked the Netlify preview and it looks like the image is the wrong size.
> 
> Your image: https://deploy-preview-226--hacktoberfest-finder.netlify.app/img/issuefinder.png The current image: https://hacktoberfest-finder.netlify.app/img/issuefinder.png
> 
> The current one is a rectangular image whereas your one is a square. I'd prefer if we kept to the same size, if possible. (1200 x 630)

As we discussed to make a generic image [which is basically meant for social share] I took the generic social media post size. Because this one is actually gonna be used in the `og` tags ! Should I still change it to the 1200 x 630 ?

**Comment by duncanmcclean** [comment]
Yes please - just want to keep it the same as it is now.

**Comment by faran4engg** [comment]
> Yes please - just want to keep it the same as it is now.

Cool. I'll update it. Thanks

**Comment by faran4engg** [comment]
> > Yes please - just want to keep it the same as it is now.
> 
> Cool. I'll update it. Thanks

# Hi @duncanmcclean , I hope this image will be fine :)
issuefinder

**Comment by faran4engg** [comment]
> Merged - thanks!

@duncanmcclean, Can you also assign it to me please !

**Pull request merged**
